name: pyrion_tool
description: "A tool to manage a Pyrion ESC"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  auto_route: ^10.2.0
  bloc: ^9.1.0
  bloc_concurrency: ^0.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.2
  grpc: ^4.3.0
  intl: ^0.20.2
  ioc_container: ^1.0.12
  logging: ^1.3.0
  meta: ^1.17.0
  protobuf: ^5.0.0
  provider: ^6.1.5+1
  shadcn_ui: ^0.38.5
  stream_transform: ^2.1.1
  window_manager: ^0.5.1

dev_dependencies:
  auto_route_generator: ^10.2.5
  build_runner: ^2.10.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  lean_builder: ^0.1.2

flutter:
  generate: true
  uses-material-design: true
