name: bldc_tool
description: "A tool to manage a BLDC"
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  auto_route: ^10.2.0
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  provider: ^6.1.5+1
  ioc_container: ^1.0.12
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lean_builder: ^0.1.2
  auto_route_generator: ^10.2.5
  build_runner: ^2.10.0

flutter:
  generate: true

  uses-material-design: true

  assets:
    - lib/assets/images/

  fonts:
    - family: Athiti
      fonts:
        - asset: lib/assets/fonts/Athiti/Athiti-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/Athiti/Athiti-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Athiti/Athiti-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Athiti/Athiti-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Athiti/Athiti-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Athiti/Athiti-Bold.ttf
          weight: 700

    - family: Cabin
      fonts:
        - asset: lib/assets/fonts/Cabin/Cabin-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Cabin/Cabin-Italic.ttf
          weight: 400
          style: italic
        - asset: lib/assets/fonts/Cabin/Cabin-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Cabin/Cabin-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/assets/fonts/Cabin/Cabin-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Cabin/Cabin-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: lib/assets/fonts/Cabin/Cabin-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Cabin/Cabin-BoldItalic.ttf
          weight: 700
          style: italic
